[package]
name = "anisearch-bot"
version.workspace = true
edition.workspace = true

[dependencies]
anisearch-entity = { path = "../anisearch-entity" }
anisearch-lib = { path = "../anisearch-lib" }
anisearch-migration = { path = "../anisearch-migration" }

anyhow.workspace = true
chrono.workspace = true
sea-orm.workspace = true
serde.workspace = true
tracing-subscriber.workspace = true
tracing.workspace = true

poise = { git = "https://github.com/serenity-rs/poise", branch = "serenity-next" }
thiserror = "2.0"
tokio = { version = "1.45", features = ["full"] }
