[package]
name = "anisearch-bot"
version.workspace = true
edition.workspace = true

[dependencies]
anisearch-entity = { path = "../anisearch-entity" }
anisearch-migration = { path = "../anisearch-migration" }

sea-orm.workspace = true

anyhow = "1.0"
chrono = "0.4"
poise = { git = "https://github.com/serenity-rs/poise", branch = "serenity-next" }
thiserror = "2.0"
tokio = { version = "1.45", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"

[build-dependencies]
chrono = "0.4"
