[workspace]
resolver = "3"
members = ["anisearch-bot", "anisearch-entity", "anisearch-migration"]

[workspace.package]
version = "3.0.0"
edition = "2024"

[workspace.dependencies]
sea-orm = { version = "1.1", features = ["macros", "runtime-tokio-rustls", "sqlx-postgres"] }
sea-orm-migration = { version = "1.1", features = ["runtime-tokio-rustls", "sqlx-postgres"] }
