[package]
name = "anisearch-web"
version.workspace = true
edition.workspace = true

[dependencies]
anisearch-lib = { path = "../anisearch-lib" }

anyhow.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing-subscriber.workspace = true
tracing.workspace = true

axum = "0.8"
