//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "guilds")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    pub added_at: DateTime,
    pub modified_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::guild_command_usages::Entity")]
    GuildCommandUsages,
}

impl Related<super::guild_command_usages::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GuildCommandUsages.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
