import os

BOT_TOKEN = os.getenv('BOT_TOKEN')
BOT_OWNER_ID = os.getenv('BOT_OWNER_ID')
BOT_SAUCENAO_API_KEY = os.getenv('BOT_SAUCENAO_API_KEY')
BOT_TOPGG_TOKEN = os.getenv('BOT_TOPGG_TOKEN')
BOT_LEVEL = os.getenv('BOT_LEVEL')
BOT_API_HOST = os.getenv('BOT_API_HOST')
BOT_API_PORT = os.getenv('BOT_API_PORT')
BOT_API_SECRET_KEY = os.getenv('BOT_API_SECRET_KEY')

DB_HOST = os.getenv('POSTGRES_HOST')
DB_PORT = os.getenv('POSTGRES_PORT')
DB_NAME = os.getenv('POSTGRES_DB')
DB_USER = os.getenv('POSTGRES_USER')
DB_PASSWORD = os.getenv('POSTGRES_PASSWORD')
